FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN pip install --no-cache-dir pipenv

COPY Pipfile /app/Pipfile
RUN pipenv install --system

COPY backend /app/backend

EXPOSE 8000

CMD ["uvicorn", "backend.main:backend", "--host", "0.0.0.0", "--port", "8000"]
